// Mocks generated by Mockito 5.4.4 from annotations
// in tumblelog/test/features/monitoring/domain/usecases/load_athletes.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tumblelog/core/entities/app_user_entity.dart' as _i5;
import 'package:tumblelog/features/monitoring/domain/repositories/athlete_repository.dart'
    as _i2;
import 'package:tumblelog/features/monitoring/domain/usecases/load_athletes.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAthleteRepository_0 extends _i1.SmartFake
    implements _i2.AthleteRepository {
  _FakeAthleteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadAthletesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadAthletesUseCase extends _i1.Mock
    implements _i3.LoadAthletesUseCase {
  MockLoadAthletesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AthleteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAthleteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AthleteRepository);

  @override
  _i4.Future<List<_i5.AppUser>> execute(String? userClub) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [userClub],
        ),
        returnValue: _i4.Future<List<_i5.AppUser>>.value(<_i5.AppUser>[]),
      ) as _i4.Future<List<_i5.AppUser>>);
}
