import 'package:tumblelog/models/skill_model.dart';

List<Skill> defaultSkills = [
  Skill(name: 'Round-off', symbol: '(', difficulty: 0.1),
  Skill(name: 'Front Handspring', symbol: 'H', difficulty: 0.1),
  Skill(name: 'Flic-Flac', symbol: 'F', difficulty: 0.1),
  Skill(name: 'Whipback (tempo salto)', symbol: '^', difficulty: 0.2),
  Skill(name: 'Back somersault tuck', symbol: '-o', difficulty: 0.5),
  Skill(name: 'Back somersault pike', symbol: '-<', difficulty: 0.6),
  Skill(name: 'Back somersault straight', symbol: '-/', difficulty: 0.6),
  Skill(name: 'Front somersault tuck', symbol: '.-o', difficulty: 0.6),
  Skill(name: 'Front somersault pike', symbol: '.-<', difficulty: 0.7),
  Skill(name: 'Side somersault tuck', symbol: '-ox', difficulty: 0.5),
  Skill(name: 'Side somersault pike', symbol: '-<x', difficulty: 0.6),
  Skill(name: 'Back somersault ½ twist', symbol: '1.-/', difficulty: 0.7),
  Skill(name: 'Barani', symbol: '.1', difficulty: 0.8),
  Skill(name: 'Back somersault 1/1 twist', symbol: '2.', difficulty: 0.9),
  Skill(name: 'Front somersault 1/1 twist', symbol: '.2', difficulty: 1.0),
  Skill(name: 'Back somersault 1½ twist', symbol: '3.', difficulty: 1.1),
  Skill(name: 'Front somersault 1½ twist', symbol: '.3', difficulty: 1.2),
  Skill(name: 'Back somersault 2/1 twist', symbol: '4.', difficulty: 1.3),
  Skill(name: 'Front somersault 2/1 twist', symbol: '.4', difficulty: 1.4),
  Skill(name: 'Back somersault 2½ twist', symbol: '5.', difficulty: 1.6),
  Skill(name: 'Back somersault 3/1 twist', symbol: '6.', difficulty: 1.9),
  Skill(name: 'Back somersault 3½ twist', symbol: '7.', difficulty: 2.3),
  Skill(name: 'Back somersault 4/1 twist', symbol: '8.', difficulty: 2.7),
  Skill(name: 'Double back somersault tuck', symbol: '--o', difficulty: 2.0),
  Skill(name: 'Double back somersault pike', symbol: '--<', difficulty: 2.2),
  Skill(
      name: 'Double back somersault straight', symbol: '--/', difficulty: 2.4),
  Skill(name: 'Full-in back-out tuck', symbol: '2-o', difficulty: 2.4),
  Skill(name: 'Full-in back-out pike', symbol: '2-<', difficulty: 2.6),
  Skill(name: 'Full-in back-out straight', symbol: '2-/', difficulty: 2.8),
  Skill(name: 'Full-in Full-out tuck', symbol: '2 2 o', difficulty: 3.2),
  Skill(name: 'Full-in Full-out straight', symbol: '2 2 /', difficulty: 3.6),
];
